# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb961650695534f01a951415b98a3bd21d9a239248f5fbd28aac0411f4d67a7d40dea60343a8806d055ef063a037c380a72b98c98591fd95e894b6e7378574ec

test:
  secret_key_base: 20214321ebf517ac639afe5583a49c17c43bee66a7aa3d78be8a42db48b2dfb5fc203d0ed84df9cd375dac091947535dd9490304159497538bddf16ebca608be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
